theme: jekyll-theme-minimal
title: <a href="https://github.com/cwolfbrandt">Carly Wolfbrandt</a> # your name (or website title) here
logo: "/images/headshot.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Scientist
  <br>
  Computational Chemist
  <br>
  To get in touch, please reach out via LinkedIn.
  <br>
  <a href="https://www.linkedin.com/in/carly-wolfbrandt/">View My LinkedIn Profile</a>
theme: jekyll-theme-minimal
